import Head from "next/head";
import BlogList from "../components/BlogList";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Script from "next/script";

export default function Home({ posts, total_posts, total_pages }) {
    return (
        <div>
            <Head>
                <title>Coder&apos;s Desideata | Be more than code</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <main className={"antialiased text-gray-900 overflow-clip"}>
                <div className="container mx-auto bg-white px-5">
                    <div className={"mt-5 py-5 text-center"}>
                        <h1 className={"site-title text-4xl mb-1.5"}>
                            Coder&apos;s Desiderata
                        </h1>
                        <div>Be more than code.</div>
                    </div>

                    <nav
                        className={
                            "border-solid border-t-2 border-b-2 border-gray-600 mb-9"
                        }
                    >
                        <ul className={"flex py-3 justify-center"}>
                            <li className={"mr-6"}>
                                <Link href="/">
                                    <a>Home</a>
                                </Link>
                            </li>
                            <li className={"mr-6"}>
                                <Link href="/">
                                    <a>Engineering</a>
                                </Link>
                            </li>
                            <li className={"mr-6"}>
                                <Link href="/">
                                    <a>Gaming</a>
                                </Link>
                            </li>
                            <li className={"mr-6"}>
                                <Link href="/">
                                    <a>Journey</a>
                                </Link>
                            </li>
                            <li className={"mr-6"}>
                                <Link href="/">
                                    <a>Learning</a>
                                </Link>
                            </li>
                            <li className={"mr-6"}>
                                <Link href="/">
                                    <a>Portfolio</a>
                                </Link>
                            </li>
                            <li className={"mr-6"}>
                                <Link href="/">
                                    <a>About</a>
                                </Link>
                            </li>
                        </ul>
                    </nav>
                    <div className={"grid grid-cols-12"}>
                        <div className="lg:col-start-4 lg:col-end-10 sm:col-start-1 sm:col-end-7">
                            <BlogList
                                posts={posts}
                                total_posts={total_posts}
                                total_pages={total_pages}
                            />
                        </div>
                    </div>
                </div>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
}

const fetch_posts = async (page_num: number) => {
    const res = await fetch(
        "https://codersdesiderata.com/wp-json/wp/v2/posts?page=" + page_num
    );
    const fetched_posts = await res.json();
    const total_posts: number = parseInt(res.headers.get("X-WP-Total") || "");
    const total_pages: number = parseInt(
        res.headers.get("X-WP-TotalPages") || ""
    );

    console.log({ total_pages });

    return { fetched_posts, total_posts, total_pages };
};

export async function getStaticProps() {
    let page_num: number = 0;
    let posts: any = [];
    let total_pages: number = 1; // There is at least one page
    let total_posts: number = 0;

    console.table({ page_num, total_pages });
    while (page_num < total_pages) {
        page_num++;
        let fetched_posts = [];

        ({ fetched_posts, total_posts, total_pages } = await fetch_posts(
            page_num
        ));

        posts = posts.concat(fetched_posts);
    }
    console.log(posts.length);

    return {
        props: {
            posts,
            total_posts,
            total_pages,
        },
    };
}
